#!/usr/bin/env bash
# =============================================================================
# PAVE — one-time setup helper for your own Databricks workspace.
#
# Prompts for the few workspace-specific values PAVE needs, writes a local
# `.env` (gitignored), and prints the exact `databricks bundle deploy` command
# to run — so you never have to hand-edit databricks.yml.
#
# Usage:  ./setup.sh
# Prereqs: Databricks CLI (`databricks -v`) authenticated to a profile
#          (`databricks auth login`), and Python 3.10+ for local runs.
# =============================================================================
set -euo pipefail

echo "PAVE — Platform Asset Vending Engine · setup"
echo "--------------------------------------------"
echo "Press Enter to accept the [default] where shown."
echo

ask() { # ask VAR "Prompt" "default"
  local __var="$1" __prompt="$2" __default="${3:-}" __val
  if [ -n "$__default" ]; then
    read -r -p "$__prompt [$__default]: " __val || true
    __val="${__val:-$__default}"
  else
    read -r -p "$__prompt: " __val || true
  fi
  printf -v "$__var" '%s' "$__val"
}

ask PROFILE          "Databricks CLI profile (supplies the workspace host)" "DEFAULT"
ask PARENT_CATALOG   "UC catalog PAVE provisions into (e.g. main)"          "main"
ask AUDIT_CATALOG    "UC catalog for PAVE's audit/registry mirror"          "${PARENT_CATALOG:-main}"
ask AUDIT_SCHEMA     "Schema for the audit/registry mirror"                 "pave"
ask PAVE_SCHEMA      "Schema PAVE owns for operational state"               "pave"
# Warehouse + Lakebase are REQUIRED — the app resource binds to both; a blank value
# fails `bundle deploy`. Loop until the customer provides them.
require() { # require VAR "Prompt"
  local __v=""
  while [ -z "$__v" ]; do
    read -r -p "$2 (required): " __v || true
  done
  printf -v "$1" '%s' "$__v"
}
require WAREHOUSE_ID     "SQL warehouse ID (create one first if needed)"
require LAKEBASE_INSTANCE "Lakebase (managed Postgres) instance name (create one first if needed)"
ask ALLOW_REAL       "Enable REAL provisioning now? (creates resources) 0/1" "0"

# ---- write .env for local dev ----------------------------------------------
cat > .env <<EOF
# Generated by setup.sh — local dev config (gitignored). Safe to edit/regenerate.
DATABRICKS_CONFIG_PROFILE=${PROFILE}
PARENT_CATALOG=${PARENT_CATALOG}
AUDIT_CATALOG=${AUDIT_CATALOG}
AUDIT_SCHEMA=${AUDIT_SCHEMA}
PAVE_SCHEMA=${PAVE_SCHEMA}
LAKEBASE_INSTANCE=${LAKEBASE_INSTANCE}
DATABRICKS_WAREHOUSE_ID=${WAREHOUSE_ID}
PROVISION_MODE=inprocess
PAVE_ALLOW_REAL=${ALLOW_REAL}
EOF
echo
echo "Wrote .env (gitignored)."

# ---- print the deploy command ----------------------------------------------
VARS="catalog=${AUDIT_CATALOG},parent_catalog=${PARENT_CATALOG}"
[ -n "${WAREHOUSE_ID}" ]      && VARS="${VARS},warehouse_id=${WAREHOUSE_ID}"
[ -n "${LAKEBASE_INSTANCE}" ] && VARS="${VARS},lakebase_instance_name=${LAKEBASE_INSTANCE}"

cat <<EOF

Next steps
----------
1) Run locally (safe, simulated — no workspace changes):
     cd src/app && python3 -m uvicorn backend.main:app --port 8731
     open http://127.0.0.1:8731

2) IMPORTANT for persistence: set LAKEBASE_INSTANCE in src/app/app.yaml to
   "${LAKEBASE_INSTANCE}" — app.yaml is uploaded as-is (no \${var} substitution), so the
   bundle var alone does NOT reach the deployed app. If left blank the app runs in
   in-memory demo mode and loses data on restart. Also set PARENT_CATALOG / AUDIT_CATALOG
   there. (Optional: APPROVERS, APP_URL, SMTP_*, PAVE_TARGET_WORKSPACES for extra features.)

3) Set your workspace host once in databricks.yml (targets.dev.workspace.host),
   then deploy — this is TWO steps (bundle deploy alone does NOT run the app):
     databricks bundle validate -t dev -p ${PROFILE} --var "${VARS}"
     databricks bundle deploy   -t dev -p ${PROFILE} --var "${VARS}"
     databricks bundle run pave -t dev -p ${PROFILE}         # deploy app to compute + start
     databricks apps get pave -p ${PROFILE} | grep -i url    # find the running URL

Note: real provisioning stays OFF until PAVE_ALLOW_REAL=1 (currently ${ALLOW_REAL}).
EOF
